# Site settings
title: Nabil's Blog
header-img: img/home-bg.jpg
email: bouab.nabil@gmail.com
description: ""
baseurl: ""
url: ""
twitter_username: 
github_username:  
facebook_username:  nabil.bouab
site_pro: "http://wwwetu.utc.fr/~nbouabda"

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
